apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fm79teaic-go
  janus-idp.io/tekton: fm79teaic-go
  backstage.io/kubernetes-id: fm79teaic-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fm79teaic-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
